"""
ForgeShield AI — Mock Data Generator
======================================
Generates realistic demo documents for the hackathon showcase:
  1. genuine_salary_slip.pdf     — Clean, authentic salary slip
  2. tampered_salary_slip.pdf    — Salary inflated by modifying income field
  3. bank_statement.pdf          — Statement with lower credits than declared income
  4. land_record.pdf             — Property deed with valuation data

Run:  python generate_samples.py
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "samples"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_all():
    print("ForgeShield AI — Generating mock data samples...")
    gen_genuine_salary_slip()
    gen_tampered_salary_slip()
    gen_bank_statement()
    gen_land_record()
    gen_itr()
    print(f"\n[OK] All samples saved to: {OUTPUT_DIR}")


def gen_genuine_salary_slip():
    """Genuine salary slip: Net salary ₹85,000/month."""
    _create_pdf(
        OUTPUT_DIR / "genuine_salary_slip.pdf",
        lines=[
            "GREENTECH SOLUTIONS PRIVATE LIMITED",
            "Corporate Office: 42 MG Road, Bengaluru - 560001",
            "",
            "SALARY SLIP — JUNE 2025",
            "Generated by: SAP HCM Payroll | CreationDate: 2025-07-01",
            "",
            f"Employee Name     : Rajesh Kumar",
            f"Employee ID       : EMP-04521",
            f"Designation       : Software Engineer",
            f"Department        : Technology",
            f"PAN               : ABCDE1234F",
            f"Bank Account      : 3891245670",
            f"IFSC Code         : CNRB0004521",
            "",
            "EARNINGS",
            f"Basic Pay                     : Rs. 55,000",
            f"House Rent Allowance          : Rs. 15,000",
            f"Transport Allowance           : Rs.  5,000",
            f"Medical Allowance             : Rs.  3,000",
            f"Special Allowance             : Rs.  7,000",
            f"-----------------------------------------",
            f"GROSS SALARY                  : Rs. 85,000",
            "",
            "DEDUCTIONS",
            f"Provident Fund (PF)           : Rs.  5,400",
            f"Professional Tax              : Rs.    200",
            f"Income Tax (TDS)              : Rs.  8,500",
            f"-----------------------------------------",
            f"TOTAL DEDUCTIONS              : Rs. 14,100",
            "",
            f"NET SALARY (Take Home)        : Rs. 70,900",
            "",
            "This is a system-generated document and does not require a signature.",
        ],
        creator="SAP HCM Payroll System",
        producer="SAP Crystal Reports 2020",
        creation_date="D:20250701000000+05'30'",
        mod_date="D:20250701000000+05'30'",
    )
    print("  [OK] genuine_salary_slip.pdf")


def gen_tampered_salary_slip():
    """
    Tampered salary slip: Income artificially inflated from ₹85,000 to ₹1,85,000.
    Metadata will show it was modified after creation (suspicious ModDate).
    """
    _create_pdf(
        OUTPUT_DIR / "tampered_salary_slip.pdf",
        lines=[
            "GREENTECH SOLUTIONS PRIVATE LIMITED",
            "Corporate Office: 42 MG Road, Bengaluru - 560001",
            "",
            "SALARY SLIP — JUNE 2025",
            "Generated by: SAP HCM Payroll | CreationDate: 2025-07-01",
            "",
            f"Employee Name     : Rajesh Kumar",
            f"Employee ID       : EMP-04521",
            f"Designation       : Software Engineer",
            f"Department        : Technology",
            f"PAN               : ABCDE1234F",
            f"Bank Account      : 3891245670",
            f"IFSC Code         : CNRB0004521",
            "",
            "EARNINGS",
            f"Basic Pay                     : Rs. 1,20,000",  # INFLATED
            f"House Rent Allowance          : Rs.   30,000",  # INFLATED
            f"Transport Allowance           : Rs.   10,000",  # INFLATED
            f"Medical Allowance             : Rs.    5,000",  # INFLATED
            f"Special Allowance             : Rs.   20,000",  # INFLATED
            f"-----------------------------------------",
            f"GROSS SALARY                  : Rs. 1,85,000",  # INFLATED (was 85k)
            "",
            "DEDUCTIONS",
            f"Provident Fund (PF)           : Rs.  14,400",
            f"Professional Tax              : Rs.     200",
            f"Income Tax (TDS)              : Rs.  25,000",
            f"-----------------------------------------",
            f"TOTAL DEDUCTIONS              : Rs.  39,600",
            "",
            f"NET SALARY (Take Home)        : Rs. 1,45,400",  # INFLATED
            "",
            "This is a system-generated document and does not require a signature.",
        ],
        creator="SAP HCM Payroll System",
        producer="Adobe Acrobat 23.0",              # Suspicious: PDF editor
        creation_date="D:20250701000000+05'30'",
        mod_date="D:20250901143022+05'30'",          # Suspicious: Modified 2 months later
    )
    print("  [OK] tampered_salary_slip.pdf  [TAMPERED — income inflated + Adobe Acrobat ModDate]")


def gen_bank_statement():
    """Bank statement showing avg monthly credit of only ₹85,000 (contradicts inflated salary)."""
    lines = [
        "CANARA BANK",
        "Statement of Account",
        "Account No: 3891245670 | IFSC: CNRB0004521",
        "Account Holder: RAJESH KUMAR",
        "Statement Period: 01-Jan-2025 to 30-Jun-2025",
        "",
        "-----------------------------------------────────────────────────────",
        "Date          Description                   Credit      Debit       Balance",
        "-----------------------------------------────────────────────────────",
    ]

    # Generate 6 months of realistic transactions
    balance = 45000.0
    months = [
        ("Jan 2025", 85200, [12000, 8500, 3000, 2200, 1500]),
        ("Feb 2025", 85200, [12000, 8500, 3000, 2200, 5000]),
        ("Mar 2025", 84800, [12000, 8500, 3000, 2200, 4500]),
        ("Apr 2025", 85200, [12000, 8500, 3000, 2200, 6000]),
        ("May 2025", 85200, [12000, 8500, 3000, 2200, 3500]),
        ("Jun 2025", 85200, [12000, 8500, 3000, 2200, 7000]),
    ]

    for month, salary, debits in months:
        balance += salary
        lines.append(f"01-{month[:3]}-25  SALARY CREDIT - GREENTECH  {salary:>10,}               {balance:>12,.2f}  Cr")
        for i, debit in enumerate(debits):
            balance -= debit
            desc = ["EMI-Home Loan", "Electricity Bill", "Grocery", "Insurance", "Online Transfer"][i]
            lines.append(f"10-{month[:3]}-25  {desc:<30}              {debit:>8,}   {balance:>12,.2f}  Cr")
        lines.append("")

    total_credits = sum(m[1] for m in months)
    avg_credit = total_credits / 6
    lines.extend([
        "-----------------------------------------────────────────────────────",
        f"Total Credits (6 months): Rs. {total_credits:,.0f}",
        f"Average Monthly Credit  : Rs. {avg_credit:,.0f}",
        f"Closing Balance         : Rs. {balance:,.2f}",
        "",
        "This is a computer-generated statement. No signature required.",
    ])

    _create_pdf(
        OUTPUT_DIR / "bank_statement.pdf",
        lines=lines,
        creator="Canara Bank CBS System",
        producer="Canara Bank Digital Banking",
        creation_date="D:20250701000000+05'30'",
        mod_date="D:20250701000000+05'30'",
    )
    print(f"  [OK] bank_statement.pdf  [Avg monthly credit: Rs. {avg_credit:,.0f} — contradicts inflated salary]")


def gen_land_record():
    """Land record / property deed."""
    _create_pdf(
        OUTPUT_DIR / "land_record.pdf",
        lines=[
            "GOVERNMENT OF KARNATAKA",
            "Department of Stamps and Registration",
            "Sale Deed / Property Registration Document",
            "",
            "Document No   : SRO/BLR/2024/45871",
            "Registration Date: 15-March-2024",
            "",
            "PROPERTY DETAILS",
            "Survey No     : 142/3A",
            "Village       : Whitefield, Bengaluru East",
            "District      : Bengaluru Urban",
            "Area          : 1200 Sq. Ft. (BUA)",
            "",
            "SELLER",
            "Name          : Karnataka Housing Board",
            "Address       : 1st Stage, Indiranagar, Bengaluru",
            "",
            "BUYER (APPLICANT)",
            "Name          : Rajesh Kumar",
            "PAN           : ABCDE1234F",
            "Address       : 45/2, 2nd Cross, Jayanagar, Bengaluru - 560041",
            "",
            "CONSIDERATION",
            "Declared Sale Price   : Rs. 45,00,000",
            "Guideline Value       : Rs. 42,00,000",
            "Stamp Duty Paid       : Rs.  2,25,000",
            "Registration Fee      : Rs.     45,000",
            "",
            "Market Value (Declared): Rs. 45,00,000",
            "",
            "Registering Authority: Sub-Registrar, Whitefield",
            "This is a certified copy of the registered document.",
        ],
        creator="Karnataka Kaveri Registration Portal",
        producer="Karnataka e-Registration System",
        creation_date="D:20240315000000+05'30'",
        mod_date="D:20240315000000+05'30'",
    )
    print("  [OK] land_record.pdf")


def gen_itr():
    """ITR Form 16 / Income Tax Return showing annual income ₹12,00,000 (= ₹1,00,000/month)."""
    _create_pdf(
        OUTPUT_DIR / "itr_form16.pdf",
        lines=[
            "FORM 16 — CERTIFICATE OF TAX DEDUCTED AT SOURCE",
            "Under Section 203 of the Income Tax Act, 1961",
            "",
            "Assessment Year: 2024-25 | Financial Year: 2023-24",
            "",
            "PART A — Details of Tax Deducted and Deposited",
            "",
            "Employer (Deductor)",
            "Name          : GREENTECH SOLUTIONS PRIVATE LIMITED",
            "TAN           : BLRG12345A",
            "PAN           : AAACG1234D",
            "Address       : 42 MG Road, Bengaluru - 560001",
            "",
            "Employee (Deductee)",
            "Name          : RAJESH KUMAR",
            "PAN           : ABCDE1234F",
            "Designation   : Software Engineer",
            "",
            "PART B — Details of Salary Paid",
            "",
            "Gross Salary (FY 2023-24)         : Rs. 12,00,000",
            "  Basic Pay                        : Rs.  6,60,000",
            "  HRA                              : Rs.  1,80,000",
            "  Other Allowances                 : Rs.  3,60,000",
            "",
            "Deductions Under Chapter VI-A     : Rs.  1,50,000",
            "  80C (PF + LIC)                   : Rs.  1,50,000",
            "",
            "Taxable Income                    : Rs. 10,50,000",
            "Tax on Taxable Income             : Rs.  1,15,000",
            "TDS Deducted (FY 2023-24)         : Rs.  1,02,000",
            "",
            "Annual Income (for loan assessment): Rs. 12,00,000",
            "Monthly Equivalent               : Rs.  1,00,000",
            "",
            "Certified that tax has been deducted at source as above.",
            "Authorised Signatory: Priya Sharma, HR Director",
        ],
        creator="TRACES Portal — Income Tax Department of India",
        producer="TRACES PDF Generator v2.1",
        creation_date="D:20240601000000+05'30'",
        mod_date="D:20240601000000+05'30'",
    )
    print("  [OK] itr_form16.pdf  [Annual income Rs. 12,00,000 = Rs. 1,00,000/month]")


def _create_pdf(path: Path, lines: list[str], creator: str = "", producer: str = "",
                creation_date: str = "", mod_date: str = ""):
    """Create a simple PDF with the given text lines and metadata."""
    try:
        from fpdf import FPDF

        class ForgeShieldPDF(FPDF):
            pass

        pdf = ForgeShieldPDF()
        pdf.add_page()
        pdf.set_margins(20, 20, 20)
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.set_font("Courier", size=9)

        for line in lines:
            # Sanitize: remove non-latin-1 characters (em-dashes, etc.)
            safe_line = line.encode("latin-1", errors="replace").decode("latin-1")
            if safe_line.strip() == "":
                pdf.ln(3)
            elif safe_line.startswith("?") and len(safe_line) > 10 and safe_line[1] == "?":
                # Was a unicode separator line — replace with ASCII
                safe_line = "-" * 55
                pdf.set_font("Courier", size=9)
                pdf.cell(0, 5, safe_line, new_x="LMARGIN", new_y="NEXT")
            elif any(line.startswith(header) for header in ["EARNINGS", "DEDUCTIONS", "PART A", "PART B",
                                                             "PROPERTY DETAILS", "BUYER", "SELLER",
                                                             "CONSIDERATION", "GOVERNMENT", "CANARA BANK",
                                                             "GREENTECH", "FORM 16"]):
                pdf.set_font("Courier", "B", 10)
                pdf.cell(0, 7, safe_line, new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Courier", size=9)
            else:
                pdf.cell(0, 5, safe_line, new_x="LMARGIN", new_y="NEXT")


        raw_pdf = bytes(pdf.output())

        # Inject custom metadata using pypdf if available
        try:
            import pypdf
            from pypdf import PdfWriter, PdfReader
            import io

            reader = PdfReader(io.BytesIO(raw_pdf))
            writer = PdfWriter()
            for page in reader.pages:
                writer.add_page(page)

            writer.add_metadata({
                "/Creator": creator,
                "/Producer": producer,
                "/CreationDate": creation_date,
                "/ModDate": mod_date,
                "/Author": "ForgeShield Mock Data Generator",
            })

            out_buf = io.BytesIO()
            writer.write(out_buf)
            path.write_bytes(out_buf.getvalue())
        except Exception:
            # Fallback: save raw without custom metadata
            path.write_bytes(raw_pdf)

    except ImportError:
        # fpdf2 not installed: create a simple text file placeholder
        path.with_suffix(".txt").write_text(
            "\n".join(lines),
            encoding="utf-8",
        )
        print(f"    [WARNING] fpdf2 not installed. Created TXT placeholder: {path.with_suffix('.txt').name}")


if __name__ == "__main__":
    generate_all()
